### ISSUE TITLE
Feature request: send template via variable other than file

### ISSUE THREAD

**Issue by santimar** [NikolaLohinski/terraform-provider-jinja#5]
Hi, i think it may be useful to have a way to use a template from a variable/local or another provider instead of just from a file.
`context.data` field already has this capability
it may be something like this

```
data "jinja_template" "render" {
  template = var.template
  context {
    // either yaml or json
    type = "yaml"
    // can be either a path or inline
    data = "${path.module}/src/context.yaml"
  }
```

**Comment by NikolaLohinski** [comment]
Hi @santimar and thank you for your interest.

I considered making it possible initially but the reason I didn't was that resolving `include` calls or using the `fileset` filter becomes impossible. The reason to that is that it's impossible to determine the template location to derive those calls from, since the template file simply does not exist.

Having said that, if you find it useful, I believe it should be fairly simple to stat the content of `template` field to check if it's a file, and if not, assume it's an in-memory template. Then, the provider could create a temporary file (in `/tmp`) and write the content to it, therefore operating the exact same way as if a template location was provided. I believe it should also log a big yellow warning about the filesystem calls issues I mentionned above.

Would that suit your needs ?

**Comment by santimar** [comment]
i already tired that way and it seemed to work, but then i had a new problem

i run my terraform within a CICD container, so every time it starts on a clean file system.
if i use the data element with a file on `/tmp/template` then when terraform refreshes the state, the file will be missing and thus the data provider give me back an error.
if i set a file on the same path where the provider is expecting a file (`/tmp/template` in this example), i get no error back (even if the file i created is empty)

right now i solved using a external python script to render my manifest
```
import json
import sys

from jinja2 import Environment, select_autoescape, BaseLoader

read = sys.stdin.read()
input_json = json.loads(read)
template = input_json.get('template')
variables = input_json.get('variables')
variables = json.loads(variables)
jinja_env = Environment(loader=BaseLoader(), autoescape=select_autoescape())
rendered = jinja_env.from_string(template).render(variables)
res = {
    "rendered_template": rendered
}
print(json.dumps(res), file=sys.stdout)
```

and then
```
data "external" "render_template" {
  program = ["python3", "${path.module}/render_template.py"]

  query = {
    # arbitrary map from strings to strings, passed
    # to the external program as the data query.
    template  = local.template
    variables = jsonencode(local.template_data)
  }
}

```

after that i can use `data.external.render_template.result.rendered_template` 

i didn't think about the context path include problem (i don't have any include on my template), so i guess there is no solution

**Comment by NikolaLohinski** [comment]
Hi @santimar 

I just created `v1.10.0` which makes it possible to pass an inlined template to the `template` field. I clearly stated everywhere in the docs that this will not behave as expected if filesystem calls are made in the template, so hopefully any consumer of this provider won't run into some funky behaviors, but you never know :shrug: 

If that covers your need, please let me know and feel free to close the issue and leave me a :star:

Cheers

**Comment by santimar** [comment]
Thanks @NikolaLohinski, i'll give a try asap and report any problems or i'll close this issue.
⭐ deserved ;)

**Comment by santimar** [comment]
I have the following template:
```
root:
  name: {{name}}
  nodes:
    {% for node_name, node in nodes.items() %}
    {{ node_name }}: {{ node.host }}
    {% endfor %}
```

and the following renderer:
```
locals {
  nodes   = {
    node1 = {
      host     = var.ip
    }
    node2 = {
      host     = var.ip
    }
  }
}

data "jinja_template" "render" {
  template = var.template
  context {
    // either yaml or json
    type = "yaml"
    // can be either a path or inline
    data = yamlencode({
      name  = var.name
      nodes = local.nodes
    })
  }
}
```
but i get the following error:
```
Error: failed to render context: failed to execute template: Unable to Execute template: Unable to execute statement at line [redacted]: nodes.items is not callable
```

am i missing something?

**Comment by NikolaLohinski** [comment]
Hi ,

Keep in mind that this provider is using an implementation of the Jinja language in Go, not the Python Jinja engine. Therefore, any calls to pythonisms such as `.items()` won't work because there's no underlying python to execute them.

For this to work, your template needs to be 100% pure Jinja. In your case, simply removing the `.items()` should work just fine in gonja and python jinja (see the second example in https://jinja.palletsprojects.com/en/3.0.x/templates/#for, though I agree it's not very clear from the docs that you don't need the `.items()` call):
```
root:
  name: {{ name }}
  nodes:
    {% for node_name, node in nodes %}
    {{ node_name }}: {{ node.host }}
    {% endfor %}
```

**Comment by santimar** [comment]
Ok, now everything seems to work, thanks!
